### ISSUE TITLE
Redundant vector copy operations

### ISSUE THREAD

**Issue by ckaspian** [RbxStu/RbxStu-V2#22]
https://github.com/RbxStu/RbxStu-V2/blob/dev/Disassembler/DisassembledChunk.cpp#L39-L65

Can be fixed via passing the vectors as reference.

```diff
- bool DisassembledChunk::ContainsInstructionChain(std::vector<const char *> szMnemonics,
-                                                  std::vector<const char *> szOperationAsString, bool bUseContains)
+ bool DisassembledChunk::ContainsInstructionChain(std::vector<const char *>& szMnemonics,
+                                                  std::vector<const char *>& szOperationAsString, bool bUseContains)
...
- std::vector<cs_insn> DisassembledChunk::GetInstructions() { return this->vInstructionsvec; }                                              
+ std::vector<cs_insn>& DisassembledChunk::GetInstructions() { return this->vInstructionsvec; }
```

**Comment by SecondNewtonLaw** [comment]
> https://github.com/RbxStu/RbxStu-V2/blob/dev/Disassembler/DisassembledChunk.cpp#L39-L65
> 
> Can be fixed via passing the vectors as reference.
> 
> ```diff
> - bool DisassembledChunk::ContainsInstructionChain(std::vector<const char *> szMnemonics,
> -                                                  std::vector<const char *> szOperationAsString, bool bUseContains)
> + bool DisassembledChunk::ContainsInstructionChain(std::vector<const char *>& szMnemonics,
> +                                                  std::vector<const char *>& szOperationAsString, bool bUseContains)
> ...
> - std::vector<cs_insn> DisassembledChunk::GetInstructions() { return this->vInstructionsvec; }                                              
> + std::vector<cs_insn>& DisassembledChunk::GetInstructions() { return this->vInstructionsvec; }
> ```

This is in purpose on the latter part, as its meant to be "immutable", I wrote it hastly so it may not be the best code either way, you can make a PR and I'll merge it no problem
