### ISSUE TITLE
[SUGGESTION] add the ability to execute without running

### ISSUE THREAD

**Issue by bitceil** [RbxStu/RbxStu-V2#26]
i have no idea how to code in c++ & cant implement this myself lmao.

**Comment by SecondNewtonLaw** [comment]
Why would this be required? Plugin debugging perhaps? The use case is too limited, I would argue, but I may add it as it could be a simple communication packet and some changes in program logic.

**Comment by SecondNewtonLaw** [comment]
Implemented on 4e124c6
